# fly.toml app configuration file generated for cv-makershakes-bot
app = 'cv-makershakes-bot'
primary_region = 'jnb'

[build]

[env]
  CLAUDE_MODEL = 'claude-sonnet-4-20250514'
  MAX_HISTORY = '20'

[processes]
  app = "python bot.py"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  auto_stop_machines = false
